### ISSUE TITLE
Question about algorithm complexity O(n^2)

### ISSUE THREAD

**Issue by alexeypetrushin** [src-d/wmd-relax#4]
Hi, thanks for sharing, it seems like because of this `doc1.similarity(doc2)` every document has to be compared with every other document. So the complexity will be O(n^2). 

So it not clear how to apply this algorithm for let's say set of million items to find similar, because it would require to do 10^6^2 = 10^12 comparisons... Do you know if there are ways to workaround that?

Thanks, Alex

**Comment by vmarkovtsev** [comment]
Hi Alex,

Yep, the theoretical complexity is O(n^2), but, in practice, it is linear. The thing is, you shouldn't use spaCy pipeline for that but rather `WMD.nearest_neighbors` method. It has many clever tricks to reduce the number of comparisons for every document. For example, in our production we've got 120k "documents", each about 200 tf-idf weighted "words", and NNs for every "document" evaluate only 100-200 others (quotes here because our domain is not NLP). Besides, to do massive all2all comparisons, you should use `WMD.cache_centroids`.

That being said, this is still not perfect at calculating the complete similarity matrix, but at least Spark-eable.

**Comment by alexeypetrushin** [comment]
Thanks!
