### ISSUE TITLE
Weights?

### ISSUE THREAD

**Issue by tvrbanec** [src-d/wmd-relax#50]
"The first element is the human-readable name of the sample, the second is an iterable with item identifiers and **the third is numpy.ndarray with the corresponding weights**."

How can one calculate weights? There is no info in referenced article.

**Comment by vmarkovtsev** [comment]
@tvrbanec this project is about calculating the distance between two *weighted* bags of words where each word is a vector and each weight is an approximation of importance. The paper mentions it as the nBOW model. If in doubt, set all weights to 1.

**Comment by tvrbanec** [comment]
Thank you for fast response and explanation. You let me think about weighting criteria. I am researching similarities between documents for several years, and until now I have never heard/read about weighting vectors/words in this task. Thanks again.

**Comment by tvrbanec** [comment]
Would you be so kind to share the code for making nbow from sentences? I would spend at least whole day to make it out, just to figure if wmd in your fast version would have any advantages over the gensim implementation.
Thanks a lot!

**Comment by vmarkovtsev** [comment]
That's TF-IDF, [gensim has it](https://radimrehurek.com/gensim/models/tfidfmodel.html). [Complete example with spacy.](http://dsgeek.com/2018/02/19/tfidf_vectors.html)

**Comment by tvrbanec** [comment]
OK, now I have everything working. But, how to get wmd similarity instead of nearest_neighbors?

**Comment by tvrbanec** [comment]
Please, just that last hint/help.

**Comment by vmarkovtsev** [comment]
Relaxation: https://github.com/src-d/wmd-relax/blob/9047f88dc3fb00b22f7f6db2176832035946ea12/wmd/__init__.py#L422

Exact: https://github.com/src-d/wmd-relax/blob/9047f88dc3fb00b22f7f6db2176832035946ea12/wmd/__init__.py#L436

These use the native implementation directly and require advanced third-party code usage and understanding skills.

Spacy example without the optimization cache: https://github.com/src-d/wmd-relax/blob/9047f88dc3fb00b22f7f6db2176832035946ea12/wmd/__init__.py#L630

This project is intended for nearest neighbours because the whole point of the code is to **not** calculate the precise distance as much as possible: it is very expensive due to cubic computational complexity of the underlying linear programming problem. So don't even try to measure the full "all to all" distance matrix, it will take you literally days.

**Comment by tvrbanec** [comment]
How can one import those functions?
