### ISSUE TITLE
why is libwmdrelax so fast?

### ISSUE THREAD

**Issue by hoangcuong2011** [src-d/wmd-relax#56]
Hi there,

Thanks for your great code. I am running  libwmdrelax and I am really impressive with how libwmdrelax is so fast compared to pyemd (https://github.com/wmayner/pyemd). I jsut have 2 quick questions that I hope to have your answer if possible.

1. How is libwmdrelax so fast? Any hint why it is the case?
2. What is _relax_cache in libwmdrelax.emd_relaxed_cache_fini(self._relax_cache), and how to utilize _relax_cache so that libwmdrelax is even faster?

Thanks!

**Comment by vmarkovtsev** [comment]
Hi, thanks for the nice feedback, it is very appreciated.

1. The heavy lifting is done by Google's ortools. It is by far superior for many classic computer science problem, e.g. TSP or linear programming. Besides, there is a quite tight bound aka "relaxation" calculated to avoid the expensive EMD evaluation - but that's used by the Python code.
2. The cache is a pure memory optimization so that the internal code does not use the heap, hence may work slightly faster. You create it with `emd[_relaxed]_cache_init` and deallocate it once you no longer need it with `emd[_relaxed]_cache_fini`. There are separate functions for the exact problem and the "relaxation" (see p.1). The init-s require the single argument - the problem size, That's your matrix size. Once the cache is created, supply it via the `cache` kwarg.

**Comment by hoangcuong2011** [comment]
Thanks @vmarkovtsev for your detail explanation!
